# Generated by Django 3.2 on 2022-01-16 23:25

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('rate_id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('DOF', 'Diaro Oficial de la Federación'), ('FXR', "Fixer'"), ('BXO', 'Banxico')], max_length=3, verbose_name='provider')),
                ('last_updated', models.DateTimeField(auto_now_add=True, verbose_name='last_updated')),
                ('value', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='value')),
                ('variant', models.PositiveIntegerField()),
            ],
        ),
    ]
