# Generated by Django 3.2 on 2022-01-17 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0002_alter_rate_rate_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='provider',
            field=models.CharField(choices=[('DOF', 'Diaro Oficial de la Federación'), ('FXR', 'Fixer'), ('BXO', 'Banxico')], max_length=3, verbose_name='provider'),
        ),
    ]
