# Generated by Django 3.2 on 2022-01-17 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0003_alter_rate_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='value',
            field=models.DecimalField(decimal_places=6, max_digits=20, verbose_name='value'),
        ),
    ]
