# Generated by Django 3.2 on 2022-01-17 08:18

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0004_alter_rate_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='last_updated_provider',
            field=models.DateTimeField(default=datetime.datetime(2022, 1, 17, 8, 18, 23, 882828, tzinfo=utc), verbose_name='last updated by provider'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='rate',
            name='last_updated',
            field=models.DateTimeField(auto_now_add=True, verbose_name='last updated'),
        ),
    ]
