# Generated by Django 3.2 on 2022-01-18 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0006_rate_variant_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='variant',
            field=models.PositiveIntegerField(verbose_name='variant'),
        ),
        migrations.AlterField(
            model_name='rate',
            name='variant_name',
            field=models.CharField(default='default', max_length=25, verbose_name='variant name'),
        ),
    ]
