# Generated by Django 3.2 on 2022-01-18 08:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rates', '0007_auto_20220118_0432'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rate',
            name='last_updated',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='last updated'),
        ),
    ]
