version: "3.9"
   
services:

  rabbitmq:
    container_name: xrate_provider_mq
    hostname: rabbitmq
    image: rabbitmq:3.9
    
    environment:
      - RABBITMQ_DEFAULT_USER
      - RABBITMQ_DEFAULT_PASS
      - RABBITMQ_DEFAULT_VHOST

    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - main

    restart: on-failure

    # Silence output a bit
    logging:
      driver: none


  postgres:
    container_name: xrate_provider_db
    hostname: postgres
    image: postgres:13
    volumes:
      - xrate_provider_db_data:/var/lib/postgresql/data
    
    ports:
      - "5432:5432"

    environment:
      - POSTGRES_DB
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      
    restart: on-failure
    networks:
      - main

    # Silence output a bit
    logging:
      driver: none

  xrate_provider_service:
    container_name: xrate_provider_service
    build: .

    #COMMENT OUT Needed for hot reload, Conflicts with .dockerignore, leaks .env
    volumes:
      - .:/apiservice
    
    environment:
      - DATABASE_URL
      - CELERY_BROKER_URL

      - DJANGO_SETTINGS_MODULE
      - SECRET_KEY

      - FIXER_API_KEY
      - BANXICO_API_KEY
      

    command: >
      bash -c "
      wait-for postgres:5432;
      python xrate_provider/manage.py runserver 0.0.0.0:8000"

    ports:
      - "8000:8000"
    networks:
      - main
    depends_on:
      - postgres

  celery_beat_combo:
    container_name: celery_beat_combo
    hostname: celery_beat_combo

    environment:
      - DATABASE_URL
      - CELERY_BROKER_URL

      - DJANGO_SETTINGS_MODULE
      - SECRET_KEY
  
      - FIXER_API_KEY
      - BANXICO_API_KEY

    build: .
   
    command: >
      bash -c "
      wait-for postgres:5432;
      celery -A xrate_provider worker -B -E -l info"

    depends_on:
      - postgres
      - rabbitmq

    deploy:
      restart_policy:
        condition: on-failure
      resources:
        limits:
          cpus: '0.50'
        reservations:
          cpus: '0.25'
          memory: 20M

    networks:
      - main

    restart: on-failure

networks:
  main:

volumes:
  xrate_provider_db_data:
