# Generated by Django 3.2 on 2022-01-17 02:49

import authentication.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='XrateApiUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.UUIDField(default=uuid.uuid4, unique=True, verbose_name='user id')),
                ('user_name', models.CharField(max_length=100, verbose_name='user name')),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='APIToken',
            fields=[
                ('key', models.CharField(default=authentication.models.make_client_token, max_length=40, primary_key=True, serialize=False, verbose_name='token')),
                ('pub_date', models.DateField(auto_now_add=True, verbose_name='issue date')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to='authentication.xrateapiuser', verbose_name='user')),
            ],
            options={
                'verbose_name': 'API token',
                'verbose_name_plural': 'API tokens',
            },
        ),
    ]
